export const zmanimLabels: Record<string, string> = {
  chatzotNight: "חצות לילה",
  alotHaShachar: "עלות השחר",
  misheyakir: "משיכיר",
  misheyakirMachmir: "משיכיר (מחמיר)",
  dawn: "דמדומים/הנץ (Dawn)",
  sunrise: "הנץ החמה",
  seaLevelSunrise: "הנץ החמה (מישור)",
  sofZmanShmaMGA19Point8: "סוף זמן ק\"ש מג\"א (19.8 מעלות)",
  sofZmanShmaMGA16Point1: "סוף זמן ק\"ש מג\"א (16.1 מעלות)",
  sofZmanShmaMGA: "סוף זמן קריאת שמע מג\"א",
  sofZmanShma: "סוף זמן קריאת שמע (גר\"א)",
  sofZmanTfillaMGA19Point8: "סוף זמן תפילה מג\"א (19.8 מעלות)",
  sofZmanTfillaMGA16Point1: "סוף זמן תפילה מג\"א (16.1 מעלות)",
  sofZmanTfillaMGA: "סוף זמן תפילה מג\"א",
  sofZmanTfilla: "סוף זמן תפילה (גר\"א)",
  chatzot: "חצות היום",
  minchaGedola: "מנחה גדולה",
  minchaGedolaMGA: "מנחה גדולה מג\"א",
  minchaKetana: "מנחה קטנה",
  minchaKetanaMGA: "מנחה קטנה מג\"א",
  plagHaMincha: "פלג המנחה",
  seaLevelSunset: "שקיעת החמה (מישור)",
  sunset: "שקיעת החמה",
  beinHaShmashos: "בין השמשות",
  dusk: "צאת הכוכבים (Dusk)",
  tzeit7083deg: "צאת הכוכבים (7.083 מעלות)",
  tzeit85deg: "צאת הכוכבים (8.5 מעלות)",
  tzeit42min: "צאת הכוכבים (42 דקות)",
  tzeit50min: "צאת הכוכבים (50 דקות)",
  tzeit72min: "צאת הכוכבים (רבנו תם - 72 דקות)"
};